"""добавлены ники

Revision ID: 739949223faf
Revises: bd9d4fc64b29
Create Date: 2026-09-02 17:30:22.045114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739949223faf'
down_revision: Union[str, Sequence[str], None] = 'bd9d4fc64b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(), server_default='#', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
