"""Добавлена индексация к некоторым таблицам

Revision ID: 8b65e739a4b8
Revises: 9c68b758f2aa
Create Date: 2026-07-08 16:02:56.157936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b65e739a4b8'
down_revision: Union[str, Sequence[str], None] = '9c68b758f2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_members_user_id'))

    # ### end Alembic commands ###
