"""add pictures table

Revision ID: d92c425550eb
Revises: 333f04a134d0
Create Date: 2026-02-05 02:14:49.707206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92c425550eb'
down_revision: Union[str, Sequence[str], None] = '333f04a134d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'date')
    # ### end Alembic commands ###
